### ISSUE TITLE
Aimbot is so good!

### ISSUE THREAD

**Issue by NoireCS** [KaylinOwO/projectnacl#2]

**Comment by waxxyTF2** [comment]
Ah yes, I found the solution.
![30841557_2014476012213321_7075594329623887872_n](https://user-images.githubusercontent.com/24618032/43988925-4c4772d2-9d0e-11e8-9cb9-4b7ccc5e78f6.jpg)

**Comment by NoireCS** [comment]
I WIN COMPETITIVE GAMES CAUSE OF YOU AND CRITICAL HITS HACKS I LOVE YOU THANK YOU KIND SIR! I WILL REMEMBER HOW U MADE ME BEST TEAM BORTRUS PLAYUR!!!!!
![15683955- - - - - - - - - - - -](https://user-images.githubusercontent.com/26226993/43988946-a6964590-9d38-11e8-8b4b-051e0def74bb.jpg)

**Comment by waxxyTF2** [comment]
No problem
![img_2504](https://user-images.githubusercontent.com/24618032/43988958-f77bb5a0-9d0e-11e8-9d6e-8151691ddef9.jpg)

**Comment by KaylinOwO** [comment]
Good to know
