### ISSUE TITLE
Failed PaintTraverse with custom member on CBaseEntity

### ISSUE THREAD

**Issue by PoLaKoSz** [KaylinOwO/projectnacl#2]
Hi!

Thank You for making this project publicly available!

When i modifiying this code part
https://github.com/KaylinOwO/projectnacl/blob/e141ebdc6e5994d8d1645183c74a842aa276ac9b/SDK.h#L760-L771
to this
``` diff
int GetOwner()
{
	DYNVAR_RETURN(int, this, "DT_BaseEntity", "m_hOwnerEntity");
}

+ int _maxHealth;

/*const char* CBaseEntity::GetModelName()
{
return gInts.ModelInfo->GetModelName(this->GetModel());
}*/
```

I get a **`Failed PaintTraverse`** error when the Visuals menu enabled (and there is a player near me). I am new to C++ but this error really weird to me because i am not even referencing anywhere  this variable. Can i get some help why this simple change break the whole program?

**Thank You!**

**Comment by pparadoxx** [comment]
you did it wrong.

**Comment by PoLaKoSz** [comment]
> you did it wrong.

Hi. Can You give me some direction so I could solve this problem, please? Thanks

**Comment by KaylinOwO** [comment]
> > you did it wrong.
> 
> Hi. Can You give me some direction so I could solve this problem, please? Thanks

If you're still having this issue all I can say is I really do advise you to switch to [Project IC](https://github.com/Lak3/ProjectIC_TF2). Project NaCl is extremely...well...just bad.

**Comment by PoLaKoSz** [comment]
Thank You for the recommendation and honesty. 👍
