### ISSUE TITLE
this isnt an issue more of a question but had no where to ask but here

### ISSUE THREAD

**Issue by OctolingNexus** [KaylinOwO/projectnacl#4]
Is it possible you still have the src to the Old nacl id love to see and feel how that was like

**Comment by KaylinOwO** [comment]
sorry for the late reply, it's pretty garbage (this last version is too, no doubt about it) but you're in luck nonetheless, found an old reupload so I put it on github, should still work fine. https://github.com/KaylinOwO/ProjectNaCl_OG
